import { writable } from 'svelte/store';

export const RANKS = [
	{ threshold: 0, emoji: '🙂', name: "Neutral Normie", color: "#fbbf24" },
	{ threshold: 500, emoji: '😃', name: "Happy Camper", color: "#fcd34d" },
	{ threshold: 2500, emoji: '😎', name: "Cool Cat", color: "#60a5fa" },
	{ threshold: 10000, emoji: '🤩', name: "Star Struck", color: "#f472b6" },
	{ threshold: 50000, emoji: '🤑', name: "Stonks Master", color: "#34d399" },
	{ threshold: 250000, emoji: '🤯', name: "Mind Blown", color: "#818cf8" },
	{ threshold: 1000000, emoji: '🤠', name: "Vibe Sheriff", color: "#fb923c" },
	{ threshold: 5000000, emoji: '👾', name: "8-Bit Legend", color: "#a78bfa" },
	{ threshold: 25000000, emoji: '👽', name: "Galactic Entity", color: "#22d3ee" },
	{ threshold: 100000000, emoji: '🧘', name: "Ascended One", color: "#e879f9" }
];

export const BUILDINGS = [
	{ id: 'cursor', name: 'Finger Gym', icon: '👆', baseCost: 15, baseProd: 0.5, desc: "Work out those fingers. Autoclicks once in a while." },
	{ id: 'grandma', name: 'Sweet Text', icon: '👵', baseCost: 100, baseProd: 3, desc: "Grandma sends wholesome emojis." },
	{ id: 'groupchat', name: 'Group Chat', icon: '📱', baseCost: 550, baseProd: 12, desc: "Chaos and vibes, mostly spam." },
	{ id: 'influencer', name: 'Influencer', icon: '🤳', baseCost: 2000, baseProd: 45, desc: "Doing it for the gram. Generates massive hype." },
	{ id: 'clown', name: 'Meme Lord', icon: '🤡', baseCost: 8000, baseProd: 120, desc: "Honk honk. The memes are flowing." },
	{ id: 'botfarm', name: 'Bot Farm', icon: '🤖', baseCost: 40000, baseProd: 350, desc: "Artificial vibes generated by the thousands." },
	{ id: 'rocket', name: 'Moon Mission', icon: '🚀', baseCost: 200000, baseProd: 1200, desc: "Taking vibes to the literal moon." },
	{ id: 'satellite', name: '5G Satellite', icon: '📡', baseCost: 1500000, baseProd: 5000, desc: "Beaming emojis directly into brains." },
	{ id: 'portal', name: 'Vibe Portal', icon: '🌀', baseCost: 20000000, baseProd: 25000, desc: "Opening rifts to the pure dimension of Joy." },
	{ id: 'garden_patch', name: 'Garden Patch', icon: '🌻', baseCost: 1000, baseProd: 0, desc: "Unlocks the Farming Tab. Grow Bio-Vibes!" }
];

export const NEWS = [
	"Local man discovers thumb muscle he didn't know existed.",
	"Scientists say emojis are the new universal language.",
	"Breaking: The moon looks like a giant cookie, wait, wrong game.",
	"Stock market crashes, invests entirely in smileys.",
	"New study shows clicking reduces stress by 0.001%.",
	"Aliens contact Earth, they only sent an eggplant emoji.",
	"Influencer apologizes for lack of vibes.",
	"Grandma learns how to use the 'fire' emoji, family concerned.",
	"Keyboard manufacturers report shortage of F keys.",
	"Vibe check passed successfully."
];

export const VEGGIE_TYPES = [
	{ id: 'carrot', emoji: '🥕', name: 'Carrot', color: '#fb923c', unlocked: true, unlockCost: 0, yield: 1, factoryRate: 1 },
	{ id: 'tomato', emoji: '🍅', name: 'Tomato', color: '#ef4444', unlocked: false, unlockCost: 500, yield: 2, factoryRate: 1.5 },
	{ id: 'corn', emoji: '🌽', name: 'Corn', color: '#fbbf24', unlocked: false, unlockCost: 1000, yield: 3, factoryRate: 2 }
];

export const FARM_MARKET = [
	{ id: 'fertilizer', name: 'Fertilizer', icon: '💩', cost: 10, desc: '+10% Global VPS & Yield', effect: (s) => 1.1, stackable: true },
	{ id: 'gmo_carrot', name: 'GMO Carrots', icon: '🧬', cost: 50, desc: 'Carrots grow 2x faster', effect: (s) => 1, stackable: true },
	{ id: 'gmo_tomato', name: 'GMO Tomatoes', icon: '🧬', cost: 50, desc: 'Tomatoes grow 2x faster', effect: (s) => 1, stackable: true },
	{ id: 'gmo_corn', name: 'GMO Corn', icon: '🧬', cost: 50, desc: 'Corn grows 2x faster', effect: (s) => 1, stackable: true },
	{ id: 'cursor_feed', name: 'Cursor Feed', icon: '💪', cost: 100, desc: '+50% Click Power', effect: (s) => 1.5, stackable: true },
	{ id: 'hover_harvest', name: 'Hover Harvest', icon: '✨', cost: 200, desc: 'Plant/harvest on hover & focus', effect: (s) => 1, stackable: false },
	{ id: 'factory', name: 'Factory', icon: '🏭', cost: 300, desc: 'Convert veggie stocks to Bio-Vibes', effect: (s) => 1, stackable: false },
	{ id: 'extra_plot', name: 'Extra Plot', icon: '🌾', cost: 500, desc: 'Add one more farming plot (cost doubles)', effect: (s) => 1, stackable: false }
];

function createGameState() {
	const defaultState = {
		vibes: 0,
		totalVibes: 0,
		startTime: Date.now(),
		inventory: {},
		farming: {
			unlocked: false,
			bioVibes: 0,
			plots: Array(9).fill().map((_, i) => ({ id: i, stage: 0, timer: 0, maxTime: 0, veggieType: 'carrot' })),
			upgrades: {},
			extraPlots: 0,
			stocks: { carrot: 0, tomato: 0, corn: 0 },
			unlockedVeggies: ['carrot'],
			factory: { enabled: false, conversionRate: 1 },
			selectedVeggieType: 'carrot'
		}
	};

	// Initialize inventory
	BUILDINGS.forEach(b => defaultState.inventory[b.id] = 0);

	const { subscribe, set, update } = writable(defaultState);

	return {
		subscribe,
		set,
		update,
		reset: () => set(defaultState),
		load: (savedState) => {
			const merged = { ...defaultState, ...savedState };
			if (!merged.farming) {
				merged.farming = {
					unlocked: false,
					bioVibes: 0,
					plots: Array(9).fill().map((_, i) => ({ id: i, stage: 0, timer: 0, maxTime: 0, veggieType: 'carrot' })),
					upgrades: {},
					extraPlots: 0,
					stocks: { carrot: 0, tomato: 0, corn: 0 },
					unlockedVeggies: ['carrot'],
					factory: { enabled: false, conversionRate: 1 },
					selectedVeggieType: 'carrot'
				};
			}
			// Ensure plots have veggieType
			if (merged.farming.plots) {
				merged.farming.plots.forEach(plot => {
					if (!plot.veggieType) plot.veggieType = 'carrot';
				});
			}
			if (merged.farming.extraPlots === undefined) merged.farming.extraPlots = 0;
			if (!merged.farming.stocks) merged.farming.stocks = { carrot: 0, tomato: 0, corn: 0 };
			if (!merged.farming.unlockedVeggies) merged.farming.unlockedVeggies = ['carrot'];
			if (!merged.farming.factory) merged.farming.factory = { enabled: false, conversionRate: 1 };
			if (!merged.farming.selectedVeggieType) merged.farming.selectedVeggieType = 'carrot';
			set(merged);
		}
	};
}

export const gameState = createGameState();

export const currentRankIndex = writable(0);

export const currentNews = writable("Welcome to the Emojiverse. Start vibing!");

export const logMessages = writable([]);
export const latestLog = writable("System Ready.");
export const logExpanded = writable(false);


